enableNoEmiMessage = false
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = true
disableItemTagTooltips = true
newVersionMessage = false
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
enableFtbQuestsIntegration = false
enableDefaultOreGenTooltips = true
datagenOnStartup = false
loadRuntimeGeneratedResources = false
removeIndustrialistTrades = false
maxDistillationTowerHeight = 9
enableInterMachineConnectedTextures = false
armorHudYPosition = 15
baseItemPipeTransfer = 16
